### ISSUE TITLE
Anita Crash on Windows 7

### ISSUE THREAD

**Issue by jromary1** [SachsenCoder/Anita#17]
Application: Anita.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: Jurassic.JavaScriptException
Stack:
   at DynamicClass.eval(Jurassic.ScriptEngine, Jurassic.Compiler.Scope, System.Object)
   at Jurassic.Compiler.EvalMethodGenerator.Execute()
   at Jurassic.ScriptEngine.Eval(System.String, Jurassic.Compiler.Scope, System.Object, Boolean)
   at Jurassic.Library.GlobalObject.Eval(Jurassic.ScriptEngine, System.Object, Jurassic.Compiler.Scope, System.Object, Boolean)
   at DynamicClass.global_(Jurassic.ScriptEngine, Jurassic.Compiler.Scope, System.Object)
   at Jurassic.Compiler.GlobalMethodGenerator.Execute()
   at Jurassic.ScriptEngine.Execute(Jurassic.ScriptSource)
   at SachsenCoder.Anita.Core.Leafs.WikifeetGrabber.processJavaScript(CsQuery.CQ, Jurassic.ScriptEngine)
   at SachsenCoder.Anita.Core.Leafs.WikifeetGrabber.FetchCelebrityPictures(SachsenCoder.Anita.Contracts.Data.CancelTarget`1<SachsenCoder.Anita.Contracts.Data.FetchCelebrityPicturesData>)
   at SachsenCoder.Anita.Core.Compositions.AsyncCancellable`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<.ctor>b__0_1(SachsenCoder.Anita.Contracts.Data.CancelTarget`1<System.__Canon>)
   at SachsenCoder.Anita.Core.Leafs.Asynchronizer`1+<>c__DisplayClass0_0[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<Input>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by ChristianG1984** [comment]
A new Release is available. Maybe, it fixes this Issue.

**Comment by jromary1** [comment]
Your new version fixed the issue. Thank you for your interest and efforts.
